#!/bin/bash
# Create Docker volumes
docker volume create postgres_data

# Run the PostgreSQL container with mounted volume
docker run --rm --name db \
  -e POSTGRES_DB=db \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=postgres \
  -p 6432:5432 \
  -v postgres_data:/var/lib/postgresql/data \
  -v $(pwd)/src/main/resources/db/migration:/docker-entrypoint-initdb.d \
  postgres:16.0

# Cleanup Docker volume (optional)
#docker volume rm postgres_data