truncate table task cascade;
truncate table event_role cascade;
truncate table event cascade;
truncate table place cascade;
truncate table "user" cascade;
truncate table role_privilege cascade;
truncate table role cascade;
truncate table privilege cascade;
truncate table registration_request cascade;